name = "edn"
version = "0.0.1"
description = "An encoding library to format Gleam values as edn"
licenses = ["Apache-2.0"]

# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
pprint = ">= 1.0.4 and < 2.0.0"
gleam_json = ">= 2.1.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
